# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Site settings
title:		           "POSSIBLE"
email:				"msk930512@snu.ac.kr"
description:	       "My first blog page"
url: 				"https://localhost:4000"
# author:              "Paul Le"
github_username:    "BenMSK"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
